[build]
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/admin"
  to = "/admin.html"
  status = 200

[[redirects]]
  from = "/marshrut"
  to = "/marshrut.html"
  status = 200

[[redirects]]
  from = "/china"
  to = "/china/index.html"
  status = 200

[[redirects]]
  from = "/.well-known/assetlinks.json"
  to = "/.well-known/assetlinks.json"
  status = 200
  force = true

[[redirects]]
  from = "/.well-known/apple-app-site-association"
  to = "/.well-known/apple-app-site-association"
  status = 200
  force = true
