-- DEPRECATED — do not apply.
-- Hotel admin columns are included in esm_bookings (see schema.sql / 001_esm_core.sql).
-- This file previously altered travel_requests (BookingMongolia-style table).
-- eSIM Mongolia must NEVER alter BookingMongolia tables.
